Feat/search
weni-ai/floweditor pull request #193
Opened 2024-02-27 15:09 UTC by acnormun

## Description
### Type of Change
* * [ ] Bugfix
* * [x] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other

### Motivation and Context
Add feature - Search Bar.

### Summary of Changes
Added a new component for searching words in send cards and their unit tests.

### Demonstration 
![image](https://github.com/weni-ai/floweditor/assets/108290807/e3eb81ab-f48c-4da6-9326-c331db763531)

2024-03-04 11:23 UTC, Aldemylla requested changes

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/Search.module.scss
Some pixels can still be replaced by unnnic tokens here

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/Search.test.tsx
> +});
Adding spaces between `describe` functions will make the code a little more readable:

```suggestion
describe(SearchBar.name, () => {
  it('should render searchbar', () => {
    const { baseElement } = render(<SearchBar {...baseProps} />);
    expect(baseElement).toMatchSnapshot();
  });

  describe('handleInput()', () => {
    it('should call handleInput', () => {
      const { getByPlaceholderText } = render(<SearchBar {...baseProps} />);
      const input = getByPlaceholderText('...');
      expect(input).toBeTruthy();
    });
  });

  describe('getAllNodes()', () => {
    it('should call getAllNodes', () => {
      const { instance } = setup(true);
      const spy = spyOn('getAllNodes');
      expect(spy).not.toHaveBeenCalled();
      instance.getAllNodes();
      expect(spy).toHaveBeenCalledTimes(1);
    });
    it('should return filtered nodes', () => {
      const { instance } = setup(true);
      const response = instance.getAllNodes();
      expect(response).toEqual(filteredNode);
    });
  });

  describe('findNodes()', () => {
    it('should call findNodes', () => {
      const { instance } = setup(true);
      const spy = spyOn('findNodes');
      expect(spy).not.toHaveBeenCalled();
      instance.findNodes('teste');
      expect(spy).toHaveBeenCalledTimes(1);
    });
    it('should return found nodes', () => {
      const { instance } = setup(true);
      const response = instance.findNodes('teste');
      expect(response).toEqual(filteredNode);
    });
  });

  describe('dragBackground()', () => {
    it('should call dragBackground', () => {
      const { instance } = setup(true);
      const spy = spyOn('dragBackground');
      expect(spy).not.toHaveBeenCalled();
      instance.dragBackground();
      expect(spy).toHaveBeenCalledTimes(1);
    });
  });

  describe('toggleMoveSelected()', () => {
    it('should call toggleMoveSelected', () => {
      const { instance } = setup(true);
      const spy = spyOn('toggleMoveSelected');
      expect(spy).not.toHaveBeenCalled();
      instance.toggleMoveSelected('up');
      expect(spy).toHaveBeenCalledTimes(1);
    });
    it('should call dragBackground', () => {
      const { instance } = setup(true);
      const spy = spyOn('dragBackground');
      expect(spy).toHaveBeenCalledTimes(2);
      instance.toggleMoveSelected('up');
      expect(spy).toHaveBeenCalledTimes(3);
    });
    it('should set search', () => {
      const { instance, props } = setup(true);
      instance.toggleMoveSelected('down');
      expect(props.search).not.toEqual({});
    });
  });

  describe('closeSearch()', () => {
    it('should call closeSearch', () => {
      const { instance } = setup(true);
      const spy = spyOn('closeSearch');
      expect(spy).not.toHaveBeenCalled();
      instance.closeSearch();
      expect(spy).toHaveBeenCalledTimes(1);
    });
  });
});
```

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/SearchBar.tsx
> +      const ui = this.props.search.nodes[this.props.search.selected].data.ui.position;
Destructuring `this.props.search` will result in fewer repetitions, which in addition to making the code more readable, will make maintenance easier:

```suggestion
    const { nodes, selected } = this.props.search
    if (nodes[selected]) {
      const ui = nodes[selected].data.ui.position;
```

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/SearchBar.tsx
> +  private toggleMoveSelected(type: 'up' | 'down') {
You could destructure `this.props.search` in this function too

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/SearchBar.tsx
> +  }
You could destructure this.props.search in this function too:
```suggestion
  private closeSearch() {
    const { value, nodes } = this.props.search;
  
    this.props.handleSearchChange({
      active: false,
      value,
      nodes,
      selected: 0
    });
  }
```

2024-03-04 11:23 UTC, Aldemylla commented on src/components/search/SearchBar.tsx
> +      </div>
Semantics is missing, could you add it?

2024-03-04 11:23 UTC, Aldemylla commented on src/components/sidebar/Sidebar.tsx
> +            </div>
Semantics is missing here too

2024-03-04 11:23 UTC, Aldemylla commented on src/flowTypes.ts
> +  [x: string]: any;
What is the meaning of "`x`", is this the most descriptive name that could be used here?

2024-04-01 20:42 UTC, Aldemylla requested changes

2024-04-01 20:42 UTC, Aldemylla commented on src/components/canvas/Canvas.module.scss
> +    #D0D3D9 1px,
```suggestion
    $unnnic-color-neutral-cleanest 0,
    $unnnic-color-neutral-cleanest 1px,
```

2024-04-01 20:42 UTC, Aldemylla commented on src/components/search/components/CloseButton.module.scss
> +        padding: 4px;
```suggestion
        padding: $unnnic-spacing-nano;
```

2024-04-01 20:42 UTC, Aldemylla commented on src/components/sidebar/components/SearchButton.module.scss
> +        border-radius: 4px;
```suggestion
        border-radius: $unnnic-border-radius-sm;
```

2024-04-01 22:01 UTC, paulobernardoaf requested changes

2024-04-02 17:22 UTC, paulobernardoaf approved these changes

2024-04-02 17:44 UTC, Aldemylla approved these changes

2024-04-02 17:45 UTC, merged