Feat/search
weni-ai/floweditor pull request #200
Opened 2024-04-09 13:17 UTC by acnormun

## Description
### Type of Change
* * [x] Bugfix
* * [ ] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other

### Motivation and Context
Removal of the browser default search card and add navigation through cards using the enter key.

### Summary of Changes
Added prevent default to Ctrl+F input and a keydown listener to search card.

2024-04-09 15:00 UTC, Aldemylla requested changes

2024-04-09 15:22 UTC, paulobernardoaf requested changes

2024-04-09 15:22 UTC, paulobernardoaf commented on src/components/search/SearchBar.tsx
> +      const down = document.querySelector('#buttons button') as HTMLButtonElement;
It's better to use a ref here instead of query selector

2024-04-09 15:22 UTC, paulobernardoaf commented on package.json
> +  "version": "2.12.0-alpha.22",
Remember to remove any alpha references before merging it into the main branch.

2024-04-09 15:22 UTC, paulobernardoaf commented on src/components/canvas/Canvas.tsx
> +      const input = (document.getElementsByClassName(
Here is alto better to use a ref to make sure that the input element used is the search input.

2024-04-09 15:22 UTC, paulobernardoaf commented on src/components/search/SearchBar.tsx
> +        <div className={styles.buttons} id="buttons">
This id becomes obsolete when switching to ref.

2024-04-11 15:02 UTC, paulobernardoaf approved these changes

2024-04-11 15:03 UTC, merged